## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    if not bld.env['ENABLE_EXAMPLES']:
        return;

    obj = bld.create_ns3_program('sample-mixture-random-variable',
                                 ['vr-app','applications'])
    obj.source = 'sample-mixture-random-variable.cc'

    obj = bld.create_ns3_program('bursty-application-example',
                                ['vr-app','applications','point-to-point','internet','network'])
    obj.source = 'bursty-application-example.cc'

    obj = bld.create_ns3_program('vr-application-example',
                                ['vr-app','applications','point-to-point','internet','network'])
    obj.source = 'vr-application-example.cc'

    obj = bld.create_ns3_program('trace-file-burst-application-example',
                                ['vr-app','applications','point-to-point','internet','network'])
    obj.source = 'trace-file-burst-application-example.cc'

    # This was originally a scratch simulation, coupled with its sem script
    obj = bld.create_ns3_program('vr-app-n-stas',
                                ['vr-app','core','applications','wifi'])
    obj.source = 'vr-app-n-stas.cc'
